Repository Zipstack/unstract, pull requests merged in 2024-10, with the labels that each got.

#751 Multitenancy V2 porting of Table settings enhancements
  backend/prompt_studio/prompt_studio_core_v2/constants.py
  backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
  backend/prompt_studio/prompt_studio_core_v2/static/select_choices.json
  backend/prompt_studio/prompt_studio_registry_v2/constants.py
  backend/prompt_studio/prompt_studio_registry_v2/prompt_studio_registry_helper.py
  backend/prompt_studio/prompt_studio_v2/models.py
Labels: MultitenantV2

#749 FEAT: Added "Run All Prompts" with Concurrent API Request Queuing Mechanism
  frontend/src/components/custom-tools/document-manager/DocumentManager.jsx
  frontend/src/components/custom-tools/editable-text/EditableText.jsx
  frontend/src/components/custom-tools/manage-docs-modal/ManageDocsModal.jsx
  frontend/src/components/custom-tools/output-for-doc-modal/OutputForDocModal.jsx
  frontend/src/components/custom-tools/prompt-card/DisplayPromptResult.jsx
  frontend/src/components/custom-tools/prompt-card/Header.jsx
  frontend/src/components/custom-tools/prompt-card/PrompDnd.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCard.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCardItems.jsx
  frontend/src/components/custom-tools/prompt-card/PromptOutput.jsx
  frontend/src/components/custom-tools/prompt-card/PromptOutputExpandBtn.jsx
  frontend/src/components/custom-tools/prompt-card/PromptOutputsModal.jsx
  frontend/src/components/custom-tools/prompt-card/PromptRun.jsx
  frontend/src/components/custom-tools/prompt-card/PromptRunCost.jsx
  frontend/src/components/custom-tools/prompt-card/PromptRunTimer.jsx
  frontend/src/components/custom-tools/prompt-card/RunAllPrompts.jsx
  frontend/src/components/custom-tools/token-usage/TokenUsage.jsx
  frontend/src/components/custom-tools/tool-ide/ToolIde.jsx
  frontend/src/components/custom-tools/tools-main/ToolsMain.jsx
  frontend/src/components/custom-tools/tools-main/ToolsMainActionBtns.jsx
  frontend/src/components/helpers/auth/PersistentLogin.js
  frontend/src/helpers/GetStaticData.js
  frontend/src/hooks/usePromptOutput.js
  frontend/src/hooks/usePromptRun.js
  frontend/src/store/custom-tool-store.js
  frontend/src/store/prompt-run-queue-store.js
  frontend/src/store/prompt-run-status-store.js
Labels: enhancement

#765 added missed json update for workflow manager endpoint v2
  backend/workflow_manager/endpoint_v2/static/dest/db.json
  backend/workflow_manager/endpoint_v2/static/src/file.json
Labels: MultitenantV2

#766 added missing migration for v2 promptsudio enforce type
  backend/prompt_studio/prompt_studio_v2/migrations/0002_alter_toolstudioprompt_enforce_type.py
Labels: MultitenantV2

#770 added type transfor for jsonb
  backend/migrating/v2/management/commands/migrate_to_v2.py
Labels: MultitenantV2

#772 pipileine v2 issue fix
  backend/pipeline_v2/migrations/0002_remove_pipeline_unique_pipeline_and_more.py
  backend/pipeline_v2/models.py
Labels: MultitenantV2

#773 handling Integrity Errors in V2 serializers
  backend/api_v2/serializers.py
  backend/pipeline_v2/serializers/crud.py
  backend/prompt_studio/prompt_studio_core_v2/serializers.py
  backend/utils/serializer/integrity_error_mixin.py
  backend/workflow_manager/endpoint_v2/models.py
  backend/workflow_manager/workflow_v2/serializers.py
  backend/workflow_manager/workflow_v2/views.py
Labels: MultitenantV2

#776 replacing cached queryset with dynamic queryset
  backend/file_management/views.py
  backend/platform_settings_v2/views.py
  backend/prompt_studio/prompt_studio_document_manager_v2/views.py
  backend/prompt_studio/prompt_studio_index_manager_v2/views.py
  backend/prompt_studio/prompt_studio_output_manager_v2/views.py
  backend/prompt_studio/prompt_studio_registry_v2/views.py
  backend/tool_instance_v2/views.py
  backend/workflow_manager/endpoint_v2/views.py
  backend/workflow_manager/workflow_v2/views.py
Labels: MultitenantV2

#781 [FIX] Passed missing param in replace_variables_in_prompt function
  prompt-service/src/unstract/prompt_service/main.py
  prompt-service/src/unstract/prompt_service/variable_extractor/base.py
Labels: MultitenantV2

#780 Replace incorrect package with the correct one
  backend/account_v2/subscription_loader.py
Labels: MultitenantV2

#779 fixes for user role change and Api key permission
  backend/account_v2/authentication_controller.py
  backend/api_v2/api_key_views.py
  backend/api_v2/permission.py
Labels: MultitenantV2

#782 [FIX] Variable replacement
  prompt-service/src/unstract/prompt_service/variable_extractor/base.py
Labels: MultitenantV2

#783 Fix for Pipeline Execution V2. Workflow Id willnot be get from API execution
  backend/scheduler/tasks.py
Labels: MultitenantV2

#785 fix: Minor account v2 related fixed to run in OSS
  .gitignore
  backend/account_v2/authentication_service.py
Labels: MultitenantV2

#790 FIX: Optimization and UI/UX Improvement of Output Analyzer
  frontend/src/components/custom-tools/combined-output/CombinedOutput.jsx
  frontend/src/components/custom-tools/combined-output/JsonView.jsx
  frontend/src/components/custom-tools/combined-output/JsonViewBody.jsx
  frontend/src/components/custom-tools/output-analyzer-header/OutputAnalyzerHeader.jsx
  frontend/src/components/custom-tools/output-analyzer-list/OutputAnalyzerList.css
  frontend/src/components/custom-tools/output-analyzer-list/OutputAnalyzerList.jsx
  frontend/src/components/custom-tools/output-analyzer/FilterPromptFields.jsx
  frontend/src/components/custom-tools/output-analyzer/OutputAnalyzer.css
  frontend/src/components/custom-tools/output-analyzer/OutputAnalyzer.jsx
  frontend/src/components/custom-tools/output-analyzer/OutputAnalyzerCard.jsx
  frontend/src/components/custom-tools/output-analyzer/OutputAnalyzerHeader.jsx
  frontend/src/pages/OutputAnalyzerPage.jsx
Labels: bug, enhancement
