Repository Zipstack/unstract, pull requests merged in 2024-07, with the labels that each got.

#441 Enhancement for prompt response metadata
  backend/api/api_deployment_views.py
  backend/api/constants.py
  backend/api/deployment_helper.py
  backend/pdm.lock
  backend/pyproject.toml
  backend/sample.env
  backend/workflow_manager/workflow/execution.py
  backend/workflow_manager/workflow/views.py
  backend/workflow_manager/workflow/workflow_helper.py
  frontend/src/components/deployments/display-code/DisplayCode.jsx
  pdm.lock
  prompt-service/pdm.lock
  prompt-service/pyproject.toml
  prompt-service/src/unstract/prompt_service/constants.py
  prompt-service/src/unstract/prompt_service/main.py
  pyproject.toml
  tools/structure/requirements.txt
  tools/structure/src/constants.py
  tools/structure/src/main.py
  unstract/tool-sandbox/src/unstract/tool_sandbox/constants.py
  unstract/tool-sandbox/src/unstract/tool_sandbox/tool_sandbox.py
  unstract/workflow-execution/src/unstract/workflow_execution/tools_utils.py
  unstract/workflow-execution/src/unstract/workflow_execution/workflow_execution.py
Labels: enhancement

#449 FEAT: Marketing Related Integration
  backend/account/authentication_controller.py
  frontend/src/hooks/useSessionValid.js
Labels: enhancement

#453 FEAT: Allow Disabling Posthog via ENV Variable
  README.md
  frontend/src/index.js
Labels: enhancement

#423 Updated README for Vector Db Milvus
  README.md
Labels: documentation

#513 [FIX] Public share fixes
  backend/prompt_studio/prompt_studio_output_manager/output_manager_helper.py
  backend/prompt_studio/prompt_studio_output_manager/views.py
  frontend/src/components/custom-tools/combined-output/CombinedOutput.jsx
  frontend/src/components/custom-tools/footer/Footer.jsx
  frontend/src/components/custom-tools/manage-docs-modal/ManageDocsModal.jsx
  frontend/src/components/custom-tools/output-analyzer-card/OutputAnalyzerCard.jsx
  frontend/src/components/custom-tools/output-analyzer-header/OutputAnalyzerHeader.jsx
  frontend/src/components/custom-tools/output-analyzer-list/OutputAnalyzerList.css
  frontend/src/components/custom-tools/output-analyzer-list/OutputAnalyzerList.jsx
  frontend/src/components/custom-tools/output-for-doc-modal/OutputForDocModal.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCard.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCardItems.jsx
  frontend/src/components/custom-tools/tool-ide/ToolIde.css
  frontend/src/components/custom-tools/tool-ide/ToolIde.jsx
Labels: bug

#426 feat: Update PostgreSQL image to include pgvector extension
  docker/docker-compose-dev-essentials.yaml
Labels: enhancement, good first issue

#529 FIX: Layout Preserving of Indexed Data Modal
  frontend/src/components/custom-tools/document-manager/DocumentManager.css
  frontend/src/components/custom-tools/prompt-card/OutputForIndex.jsx
Labels: bug
