Repository Zipstack/unstract, pull requests merged in 2024-04, with the labels that each got.

#212 Token info for Chunk Size : LLM
  frontend/src/components/custom-tools/add-llm-profile/AddLlmProfile.jsx
Labels: enhancement

#193 api deployment workflow url not working issu fix
  frontend/src/components/deployments/api-deployment/ApiDeployment.jsx
Labels: bug

#194 fix: Fixed use of --force within dev env script
  dev-env-cli.sh
Labels: bug

#197 Fix for adapter access revert
  backend/adapter_processor/views.py
Labels: bug

#200 fix: Enhanced merge env script to allow user defined envs
  docker/scripts/merge_env.py
Labels: bug

#195 Show error message when user try to add profile with existing name
  backend/prompt_studio/prompt_profile_manager/constants.py
  backend/prompt_studio/prompt_profile_manager/views.py
  frontend/src/components/custom-tools/add-llm-profile/AddLlmProfile.jsx
Labels: enhancement

#226 Prompt Studio UI enhancements
  frontend/src/components/input-output/list-of-sources/ListOfSources.jsx
  frontend/src/components/settings/settings/Settings.jsx
  frontend/src/components/widgets/list-view/ListView.css
  frontend/src/components/widgets/list-view/ListView.jsx
Labels: enhancement

#223 FIX: Prompt Studio Improvements and Bug Fixes
  frontend/src/components/custom-tools/document-manager/DocumentManager.jsx
  frontend/src/components/custom-tools/list-of-tools/ListOfTools.jsx
  frontend/src/components/custom-tools/manage-docs-modal/ManageDocsModal.jsx
  frontend/src/components/custom-tools/output-for-doc-modal/OutputForDocModal.jsx
  frontend/src/components/custom-tools/tool-ide/ToolIde.jsx
Labels: bug, enhancement

#236 Fix default value for keys during upgrade
  docker/scripts/merge_env.py
Labels: bug

#112 Authorization/Permissions Prompt studio
  backend/account/authentication_controller.py
  backend/account/serializer.py
  backend/adapter_processor/serializers.py
  backend/file_management/urls.py
  backend/file_management/views.py
  backend/prompt_studio/permission.py
  backend/prompt_studio/prompt_profile_manager/urls.py
  backend/prompt_studio/prompt_profile_manager/views.py
  backend/prompt_studio/prompt_studio/urls.py
  backend/prompt_studio/prompt_studio/views.py
  backend/prompt_studio/prompt_studio_core/constants.py
  backend/prompt_studio/prompt_studio_core/migrations/0012_customtool_shared_users.py
  backend/prompt_studio/prompt_studio_core/models.py
  backend/prompt_studio/prompt_studio_core/prompt_studio_helper.py
  backend/prompt_studio/prompt_studio_core/serializers.py
  backend/prompt_studio/prompt_studio_core/urls.py
  backend/prompt_studio/prompt_studio_core/views.py
  backend/prompt_studio/prompt_studio_document_manager/urls.py
  backend/prompt_studio/prompt_studio_document_manager/views.py
  backend/prompt_studio/prompt_studio_index_manager/urls.py
  backend/prompt_studio/prompt_studio_index_manager/views.py
  backend/prompt_studio/prompt_studio_registry/migrations/0006_promptstudioregistry_shared_to_org_and_more.py
  backend/prompt_studio/prompt_studio_registry/models.py
  backend/prompt_studio/prompt_studio_registry/prompt_studio_registry_helper.py
  backend/prompt_studio/prompt_studio_registry/serializers.py
  backend/prompt_studio/prompt_studio_registry/urls.py
  backend/prompt_studio/prompt_studio_registry/views.py
  backend/tool_instance/tool_instance_helper.py
  frontend/src/components/custom-tools/add-llm-profile/AddLlmProfile.jsx
  frontend/src/components/custom-tools/document-manager/DocumentManager.jsx
  frontend/src/components/custom-tools/header/Header.jsx
  frontend/src/components/custom-tools/list-of-tools/ListOfTools.jsx
  frontend/src/components/custom-tools/manage-docs-modal/ManageDocsModal.jsx
  frontend/src/components/custom-tools/manage-llm-profiles/ManageLlmProfiles.jsx
  frontend/src/components/custom-tools/output-analyzer-card/OutputAnalyzerCard.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCard.jsx
  frontend/src/components/custom-tools/tool-ide/ToolIde.jsx
  frontend/src/components/custom-tools/tools-main/ToolsMain.jsx
  frontend/src/components/helpers/custom-tools/CustomToolsHelper.js
  frontend/src/components/widgets/share-permission/SharePermission.css
  frontend/src/components/widgets/share-permission/SharePermission.jsx
Labels: enhancement

#196 Hide onboard banner when all adapters configured after skipping from onboard screen
  frontend/src/components/input-output/configure-ds/ConfigureDs.jsx
  frontend/src/components/navigations/top-nav-bar/TopNavBar.jsx
Labels: enhancement

#252 Fix/display error value in output viewer
  frontend/src/components/custom-tools/manage-docs-modal/ManageDocsModal.jsx
  frontend/src/components/custom-tools/output-for-doc-modal/OutputForDocModal.jsx
  frontend/src/helpers/GetStaticData.js
Labels: bug

#262 Fixed Enforce Type Issues for Boolean and JSON
  prompt-service/src/unstract/prompt_service/main.py
Labels: bug

#218 [FIX] UN-1068 Removing unused filetypes
  backend/workflow_manager/endpoint/constants.py
  backend/workflow_manager/endpoint/source.py
  backend/workflow_manager/endpoint/static/src/api.json
  backend/workflow_manager/endpoint/static/src/file.json
  tools/structure/src/config/properties.json
Labels: bug

#268 Fixed Issue in Displaying Boolean Value
  frontend/src/helpers/GetStaticData.js
Labels: bug

#293 FIX: JSON Enforce Type
  prompt-service/src/unstract/prompt_service/main.py
Labels: bug

#292 [FIX] Changing env to mountable path - PRIVATE_REGISTRY_CREDENTIAL_PATH
  worker/sample.env
  worker/src/unstract/worker/constants.py
  worker/src/unstract/worker/worker.py
Labels: bug
