Repository Zipstack/unstract, pull requests merged in 2024-03, with the labels that each got.

#206 Remove internal docker compose pull policy
  README.md
  run-platform.sh
Labels: documentation, enhancement

#204 docs: Added pdm managed badge to README.md
  README.md
Labels: documentation

#198 Fixed alignment issue and status error
  frontend/src/components/widgets/list-view/ListView.css
  frontend/src/components/widgets/list-view/ListView.jsx
  frontend/src/hooks/useSessionValid.js
Labels: bug

#202 Disabled few adapters and tagged them coming soon
  frontend/src/components/input-output/list-of-sources/ListOfSources.jsx
Labels: enhancement
