Repository Zipstack/unstract, pull requests merged in 2024-09, with the labels that each got.

#662 HOTFIX: Trigger logout when mandatory API fails.
  frontend/src/hooks/useLogout.js
  frontend/src/hooks/useSessionValid.js
  frontend/src/hooks/useUserSession.js
Labels: bug

#668 FIX: Removed Polling to Fetch Token Usage API
  frontend/src/components/custom-tools/prompt-card/PromptCard.jsx
  frontend/src/components/custom-tools/prompt-card/PromptOutput.jsx
  frontend/src/components/custom-tools/token-usage/TokenUsage.jsx
  frontend/src/hooks/useTokenUsage.js
Labels: bug

#690 FIX: Issue in Displaying Cost for Prompt Run
  frontend/src/components/custom-tools/prompt-card/PromptCard.jsx
Labels: bug

#693 FIX: Optimized the Prompt Output API Calls
  backend/prompt_studio/prompt_studio_core/prompt_studio_helper.py
  backend/prompt_studio/prompt_studio_output_manager/output_manager_helper.py
  frontend/src/components/custom-tools/document-parser/DocumentParser.jsx
  frontend/src/components/custom-tools/output-for-doc-modal/OutputForDocModal.jsx
  frontend/src/components/custom-tools/prompt-card/Header.jsx
  frontend/src/components/custom-tools/prompt-card/PrompDnd.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCard.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCardItems.jsx
  frontend/src/components/custom-tools/prompt-card/PromptOutput.jsx
  frontend/src/components/custom-tools/prompt-card/PromptOutputExpandBtn.jsx
  frontend/src/components/custom-tools/prompt-card/PromptOutputsModal.jsx
  frontend/src/components/custom-tools/tools-main/ToolsMain.jsx
  frontend/src/helpers/GetStaticData.js
  frontend/src/hooks/usePromptOutput.js
  frontend/src/store/prompt-output-store.js
  frontend/src/store/token-usage-store.js
Labels: bug

#696 FIX: Optimized the Re-rendering of the Prompt Card Component
  frontend/src/components/custom-tools/document-parser/DocumentParser.jsx
  frontend/src/components/custom-tools/editable-text/EditableText.jsx
  frontend/src/components/custom-tools/notes-card/NotesCard.jsx
  frontend/src/components/custom-tools/prompt-card/PrompDnd.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCard.jsx
  frontend/src/components/custom-tools/prompt-card/constants.js
  frontend/src/helpers/GetStaticData.js
Labels: bug

#711 FIX: Refactored the DisplayPromptResult Component
  frontend/src/components/custom-tools/prompt-card/DisplayPromptResult.jsx
  frontend/src/components/custom-tools/prompt-card/PromptCard.css
  frontend/src/components/custom-tools/prompt-card/PromptOutput.jsx
Labels: bug

#715 Included application_name when initializing db
  backend/backend/settings/base.py
  docker/docker-compose.yaml
  platform-service/src/unstract/platform_service/controller/platform.py
  platform-service/src/unstract/platform_service/env.py
  prompt-service/src/unstract/prompt_service/config.py
Labels: enhancement

#698 FIX: Optimize Timer Handling for Prompt Run API Calls
  frontend/src/components/custom-tools/prompt-card/PromptCard.jsx
  frontend/src/components/custom-tools/prompt-card/PromptOutput.jsx
  frontend/src/components/custom-tools/prompt-card/PromptRunCost.jsx
  frontend/src/components/custom-tools/prompt-card/PromptRunTimer.jsx
Labels: bug

#537 data migrations for v2 applications
  backend/migrating/v2/README.md
  backend/migrating/v2/__init__.py
  backend/migrating/v2/admin.py
  backend/migrating/v2/apps.py
  backend/migrating/v2/constants.py
  backend/migrating/v2/management/__init__.py
  backend/migrating/v2/management/commands/__init__.py
  backend/migrating/v2/management/commands/create_v2_schema.py
  backend/migrating/v2/management/commands/drop_v2_schema.py
  backend/migrating/v2/management/commands/migrate_to_v2.py
  backend/migrating/v2/migrations/__init__.py
  backend/migrating/v2/query.py
  backend/migrating/v2/unstract_migrations.py
Labels: MultitenantV2

#538 delta changes and enhancements in platform and prompt services
  backend/sample.env
  platform-service/sample.env
  platform-service/src/unstract/platform_service/controller/platform.py
  platform-service/src/unstract/platform_service/env.py
  platform-service/src/unstract/platform_service/helper/adapter_instance.py
  platform-service/src/unstract/platform_service/helper/prompt_studio.py
  prompt-service/sample.env
  prompt-service/src/unstract/prompt_service/authentication_middleware.py
  prompt-service/src/unstract/prompt_service/db_utils.py
  prompt-service/src/unstract/prompt_service/env_manager.py
  prompt-service/src/unstract/prompt_service/helper.py
  prompt-service/src/unstract/prompt_service/main.py
Labels: MultitenantV2

#630 Delta Changes for Multi-Tenancy V2 API Account Adapter applications
  backend/account_v2/authentication_controller.py
  backend/account_v2/dto.py
  backend/account_v2/serializer.py
  backend/account_v2/views.py
  backend/adapter_processor_v2/adapter_processor.py
  backend/adapter_processor_v2/constants.py
  backend/adapter_processor_v2/exceptions.py
  backend/adapter_processor_v2/models.py
  backend/adapter_processor_v2/serializers.py
  backend/adapter_processor_v2/views.py
  backend/api_v2/api_deployment_views.py
  backend/api_v2/api_key_validator.py
  backend/api_v2/api_key_views.py
  backend/api_v2/deployment_helper.py
  backend/api_v2/exceptions.py
  backend/api_v2/key_helper.py
  backend/api_v2/models.py
  backend/api_v2/notification.py
  backend/api_v2/postman_collection/constants.py
  backend/api_v2/postman_collection/dto.py
  backend/api_v2/serializers.py
  backend/api_v2/urls.py
  backend/api_v2/utils.py
  backend/notification_v2/__init__.py
  backend/notification_v2/apps.py
  backend/notification_v2/constants.py
  backend/notification_v2/enums.py
  backend/notification_v2/helper.py
  backend/notification_v2/migrations/__init__.py
  backend/notification_v2/models.py
  backend/notification_v2/provider/__init__.py
  backend/notification_v2/provider/notification_provider.py
  backend/notification_v2/provider/registry.py
  backend/notification_v2/provider/webhook/__init__.py
  backend/notification_v2/provider/webhook/api_webhook.py
  backend/notification_v2/provider/webhook/slack_webhook.py
  backend/notification_v2/provider/webhook/webhook.py
  backend/notification_v2/serializers.py
  backend/notification_v2/urls.py
  backend/notification_v2/views.py
Labels: MultitenantV2

#675 prompt-studio helper changes for v2 porting
  backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
Labels: MultitenantV2

#676 index-in-oss-without-plugin
  backend/prompt_studio/prompt_studio_core_v2/views.py
Labels: MultitenantV2

#680 multitenancy v2 delta changes for pr 535
  backend/pipeline_v2/serializers/crud.py
Labels: MultitenantV2

#686 delta changes for pipeline v2 multitenancy
  backend/pipeline_v2/deployment_helper.py
  backend/pipeline_v2/dto.py
  backend/pipeline_v2/exceptions.py
  backend/pipeline_v2/models.py
  backend/pipeline_v2/notification.py
  backend/pipeline_v2/piepline_api_execution_views.py
  backend/pipeline_v2/pipeline_processor.py
  backend/pipeline_v2/public_api_urls.py
  backend/pipeline_v2/serializers/crud.py
  backend/pipeline_v2/urls.py
  backend/pipeline_v2/views.py
Labels: MultitenantV2

#688 workflow manager endpoint v2 delta changes
  backend/workflow_manager/endpoint_v2/destination.py
  backend/workflow_manager/endpoint_v2/dto.py
  backend/workflow_manager/endpoint_v2/source.py
Labels: MultitenantV2

#689 workflow manager workflow v2 delta changes
  backend/workflow_manager/workflow_v2/execution.py
  backend/workflow_manager/workflow_v2/utils.py
  backend/workflow_manager/workflow_v2/workflow_helper.py
Labels: MultitenantV2

#712 Multitenancy v2 changes for prompt_studio_output_manager app
  backend/prompt_studio/prompt_studio_output_manager_v2/models.py
  backend/prompt_studio/prompt_studio_output_manager_v2/output_manager_helper.py
  backend/prompt_studio/prompt_studio_output_manager_v2/views.py
Labels: MultitenantV2

#718 MT-v2: Prompt studio core variable replacement minor changes from PR 611
  backend/prompt_studio/prompt_studio_core_v2/exceptions.py
  backend/prompt_studio/prompt_studio_core_v2/prompt_variable_service.py
Labels: MultitenantV2

#720 Multitenancy v2 changes for prompt studio apps - Prompt studio core, Registry
  backend/prompt_studio/prompt_studio_core_v2/constants.py
  backend/prompt_studio/prompt_studio_core_v2/exceptions.py
  backend/prompt_studio/prompt_studio_core_v2/models.py
  backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
  backend/prompt_studio/prompt_studio_core_v2/static/select_choices.json
  backend/prompt_studio/prompt_studio_core_v2/views.py
  backend/prompt_studio/prompt_studio_registry_v2/constants.py
  backend/prompt_studio/prompt_studio_registry_v2/exceptions.py
  backend/prompt_studio/prompt_studio_registry_v2/fields.py
  backend/prompt_studio/prompt_studio_registry_v2/prompt_studio_registry_helper.py
  backend/prompt_studio/prompt_studio_v2/controller.py
  backend/prompt_studio/prompt_studio_v2/helper.py
  backend/prompt_studio/prompt_studio_v2/models.py
  backend/prompt_studio/prompt_studio_v2/urls.py
  backend/prompt_studio/prompt_studio_v2/views.py
Labels: MultitenantV2

#721 MT-v2: Adapter, connector minor changes related to decryption
  backend/adapter_processor_v2/adapter_processor.py
  backend/connector_v2/connector_instance_helper.py
  backend/connector_v2/models.py
  backend/connector_v2/serializers.py
  backend/prompt_studio/prompt_studio_core_v2/constants.py
  backend/prompt_studio/prompt_studio_core_v2/models.py
Labels: MultitenantV2

#722 MT-v2: Tool instance changes from 489, 495 and 543
  backend/tool_instance_v2/serializers.py
  backend/tool_instance_v2/tool_instance_helper.py
  backend/tool_instance_v2/tool_processor.py
  backend/workflow_manager/workflow_v2/generator.py
  backend/workflow_manager/workflow_v2/views.py
Labels: MultitenantV2

#724 Multitenancy v2 changes for prompt studio apps - Prompt studio Profile Manager
  backend/prompt_studio/prompt_profile_manager_v2/serializers.py
Labels: MultitenantV2

#738 schema and settings are updated
  backend/adapter_processor_v2/migrations/0001_initial.py
  backend/api_v2/migrations/0001_initial.py
  backend/backend/settings/base.py
  backend/connector_v2/migrations/0001_initial.py
  backend/notification_v2/migrations/0001_initial.py
  backend/pipeline_v2/migrations/0001_initial.py
  backend/prompt_studio/prompt_profile_manager_v2/migrations/0001_initial.py
  backend/prompt_studio/prompt_studio_document_manager_v2/migrations/0001_initial.py
  backend/prompt_studio/prompt_studio_index_manager_v2/migrations/0001_initial.py
  backend/prompt_studio/prompt_studio_output_manager_v2/migrations/0001_initial.py
  backend/prompt_studio/prompt_studio_registry_v2/migrations/0001_initial.py
  backend/prompt_studio/prompt_studio_v2/migrations/0001_initial.py
  backend/tenant_account_v2/migrations/0001_initial.py
  backend/tool_instance_v2/migrations/0001_initial.py
  backend/usage_v2/migrations/0001_initial.py
  backend/workflow_manager/endpoint_v2/exceptions.py
  backend/workflow_manager/endpoint_v2/migrations/0001_initial.py
  backend/workflow_manager/workflow_v2/workflow_helper.py
Labels: MultitenantV2

#741 minor additions from V1 on workflow executions. Table name changes in platform and prompt
  backend/tool_instance_v2/serializers.py
  backend/workflow_manager/workflow_v2/execution.py
  backend/workflow_manager/workflow_v2/views.py
  backend/workflow_manager/workflow_v2/workflow_helper.py
  platform-service/src/unstract/platform_service/constants.py
  prompt-service/src/unstract/prompt_service/constants.py
Labels: MultitenantV2

#747 Minor fixes and url router updates
  backend/backend/public_urls_v2.py
  backend/backend/urls_v2.py
  prompt-service/src/unstract/prompt_service/helper.py
Labels: MultitenantV2

#748 MT-v2 changes for param to toggle file history usage
  backend/api_v2/api_deployment_views.py
  backend/api_v2/constants.py
  backend/api_v2/deployment_helper.py
  backend/api_v2/serializers.py
  backend/usage_v2/helper.py
  backend/workflow_manager/endpoint_v2/destination.py
  backend/workflow_manager/endpoint_v2/source.py
  backend/workflow_manager/workflow_v2/execution.py
  backend/workflow_manager/workflow_v2/workflow_helper.py
Labels: MultitenantV2

#755 added a custom DB engine for V2 to add search path
  backend/backend/custom_db/__init__.py
  backend/backend/custom_db/base.py
  backend/backend/settings/base.py
Labels: MultitenantV2

#758 Multitenancy v2 changes for prompt studio Export
  backend/prompt_studio/prompt_studio_core_v2/views.py
  backend/prompt_studio/prompt_studio_registry/prompt_studio_registry_helper.py
  backend/prompt_studio/prompt_studio_registry_v2/exceptions.py
  backend/prompt_studio/prompt_studio_registry_v2/prompt_studio_registry_helper.py
  backend/prompt_studio/prompt_studio_registry_v2/serializers.py
Labels: MultitenantV2

#759 Added missing delta in api v2
  backend/api_v2/api_deployment_views.py
  backend/api_v2/deployment_helper.py
Labels: MultitenantV2

#760 added missed delta changes
  backend/workflow_manager/endpoint_v2/constants.py
  backend/workflow_manager/endpoint_v2/database_utils.py
  backend/workflow_manager/endpoint_v2/destination.py
  backend/workflow_manager/endpoint_v2/queue_utils.py
  backend/workflow_manager/workflow_v2/constants.py
  backend/workflow_manager/workflow_v2/dto.py
  backend/workflow_manager/workflow_v2/execution.py
  backend/workflow_manager/workflow_v2/workflow_helper.py
Labels: MultitenantV2
